version: "3.8"

services:
  api:
    build: ./api
    container_name: api_container
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PORT=${PORT}
      - API_URL=${API_URL}
    depends_on:
      - redis

  redis:
    image: redis/redis-stack-server:latest
    container_name: sport-club-api-redis

  app:
    build: ./app
    container_name: app_container
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_HOST=${NEXT_PUBLIC_HOST}
